ProyectoVision: ExtractorLandmarks Class Reference
ExtractorLandmarks Class Reference abstract
Clase abstracta para extraer landmarks de un Mat.
#include <extractorlandmarks.h>
Public Member Functions
ExtractorLandmarks (const std::vector< string > &)
Construye un nuevo objeto de la clase abstracta Extractor Landmarks.
ExtractorLandmarks ()
virtual ~ExtractorLandmarks ()
Destruye el objeto de la clase Extractor Landmarks.
const std::vector< Landmarks > parseLandmarks (const std::vector< std::vector< cv::Point2f >> &)
Método para convertir los landmarks "crudos" a una estructura con distintos rasgos.
virtual const TipoExtractor getExtractor ()=0
virtual const std::vector< Landmarks > getLandmarks (const cv::Mat &frame)=0
Devuelve la propiedad Landmarks.
Private Attributes
std::vector< Landmarks > landmarks
Propiedad de las clases, vector de landmarks obtenidos.
Detailed Description
Clase abstracta para extraer landmarks de un Mat.
Constructor & Destructor Documentation
ExtractorLandmarks() [1/2]
ExtractorLandmarks::ExtractorLandmarks (const std::vector< string > & nombres)
Construye un nuevo objeto de la clase abstracta Extractor Landmarks.
ExtractorLandmarks() [2/2]
ExtractorLandmarks::ExtractorLandmarks ()
~ExtractorLandmarks()
ExtractorLandmarks::~ExtractorLandmarks () virtual
Destruye el objeto de la clase Extractor Landmarks.
Member Function Documentation
getExtractor()
virtual const TipoExtractor ExtractorLandmarks::getExtractor () pure virtual
Implemented in ExtractorLandmarksOpenCV, and ExtractorLandmarksDlib.
Referenced by AnalizadorSimetria::getExtractor(), and AnalizadorSimetria::setExtractor().
getLandmarks()
const std::vector< Landmarks > ExtractorLandmarks::getLandmarks (const cv::Mat & frame) pure virtual
Devuelve la propiedad Landmarks.
Parameters
frame
Returns
const std::vector<Landmarks>
Implemented in ExtractorLandmarksOpenCV, and ExtractorLandmarksDlib.
References landmarks.
Referenced by AnalizadorSimetria::step().
parseLandmarks()
const std::vector< Landmarks > ExtractorLandmarks::parseLandmarks (const std::vector< std::vector< cv::Point2f >> & landmarksSerie)
Método para convertir los landmarks "crudos" a una estructura con distintos rasgos.
Returns
const std::vector<Landmarks>
References Landmarks::boca, Landmarks::cejaDer, Landmarks::cejaIzq, landmarks, Landmarks::menton, Landmarks::nariz, Landmarks::ojoDer, Landmarks::ojoIzq, and Landmarks::vacio.
Referenced by ExtractorLandmarksDlib::getLandmarks(), and ExtractorLandmarksOpenCV::getLandmarks().
Member Data Documentation
landmarks
std::vector<Landmarks> ExtractorLandmarks::landmarks private
Propiedad de las clases, vector de landmarks obtenidos.
Referenced by getLandmarks(), and parseLandmarks().
The documentation for this class was generated from the following files:
extractorlandmarks.h
extractorlandmarks.cc