ProyectoVision: AnalizadorLandmarks Class Reference
AnalizadorLandmarks Class Reference
Clase que maneja los metodos para analizar los landmarks.
#include <analizadorlandmarks.h>
Public Member Functions
AnalizadorLandmarks ()
Construye un nuevo objeto de la clase Analizador Landmarks.
~AnalizadorLandmarks ()
Destruye el objeto de la clase Analizador Landmarks.
void setLandmarks (const std::vector< Landmarks > &)
Actualiza los landmarks del objeto.
const std::vector< Landmarks > getLandmarks ()
Devuelve los landmarks del objeto.
std::vector< Landmarks > getNormLandmarks ()
Devuelve los landmarks normalizados del objeto.
const float calcularAngulo (const Point2f &, const Point2f &)
Método que devuelve el angulo entre dos puntos a y b.
const float calcularPendiente (const Point2f &, const Point2f &)
Metodo que devuelve la pendiente entre dos puntos a y b.
const float calcularMax (const float &, const float &)
Método que devuelve el máximo valor entre dos puntos.
const float calcularAsimetria ()
Método principal de la clase, analiza la asimetria de un rostro.
void normalizarLandmarks ()
Funcion que normaliza los landmarks, eliminando la posible rotacion del rostro.
Private Attributes
std::vector< Landmarks > landmarks
Vector de estructuras de tipo Landmarks.
std::vector< Landmarks > landmarksNorm
Vector de estructura de tipo Landmarks, pero normalizada(sin rotacion del rostro)
Detailed Description
Clase que maneja los metodos para analizar los landmarks.
Todo:
calcular asimetria
Constructor & Destructor Documentation
AnalizadorLandmarks()
AnalizadorLandmarks::AnalizadorLandmarks ()
Construye un nuevo objeto de la clase Analizador Landmarks.
~AnalizadorLandmarks()
AnalizadorLandmarks::~AnalizadorLandmarks ()
Destruye el objeto de la clase Analizador Landmarks.
Member Function Documentation
calcularAngulo()
const float AnalizadorLandmarks::calcularAngulo (const Point2f & a, const Point2f & b) inline
Método que devuelve el angulo entre dos puntos a y b.
Parameters
a - punto a
b - punto b
Returns
const float - angulo en grandos
Referenced by normalizarLandmarks().
calcularAsimetria()
const float AnalizadorLandmarks::calcularAsimetria ()
Método principal de la clase, analiza la asimetria de un rostro.
No está completamente desarrollada, pero debería devolver una asimetría de un rostro. Lo ideal en realidad sería que devuelva una estructura con diferentes parámetros, para luego alimentar a una red neuronal y discernir la asimetria.
Returns
const float
References calcularMax(), and landmarksNorm.
Referenced by AnalizadorSimetria::step().
calcularMax()
const float AnalizadorLandmarks::calcularMax (const float & a, const float & b) inline
Método que devuelve el máximo valor entre dos puntos.
Parameters
a - punto a
b - punto b
Returns
const float - valor máximo
Referenced by calcularAsimetria().
calcularPendiente()
const float AnalizadorLandmarks::calcularPendiente (const Point2f & a, const Point2f & b) inline
Metodo que devuelve la pendiente entre dos puntos a y b.
Parameters
a - punto a
b - punto b
Returns
const float - pendiente entre los dos puntos
getLandmarks()
const std::vector<Landmarks> AnalizadorLandmarks::getLandmarks () inline
Devuelve los landmarks del objeto.
Returns
const std::vector<Landmarks>
getNormLandmarks()
std::vector<Landmarks> AnalizadorLandmarks::getNormLandmarks () inline
Devuelve los landmarks normalizados del objeto.
Returns
std::vector<Landmarks>
normalizarLandmarks()
void AnalizadorLandmarks::normalizarLandmarks ()
Funcion que normaliza los landmarks, eliminando la posible rotacion del rostro.
La normalización cobra relevancia si se toma como parámetros la pendiente o el angulo entre distintos landmarks en el rostro. Por el momento no tiene utilidad, pero en el caso de alimentar una RN cobraría relevancia.
References Landmarks::boca, calcularAngulo(), Landmarks::cejaDer, Landmarks::cejaIzq, Landmarks::escala, landmarks, landmarksNorm, Landmarks::menton, Landmarks::nariz, Landmarks::ojoDer, Landmarks::ojoIzq, and Landmarks::rotacion.
Referenced by AnalizadorSimetria::step().
setLandmarks()
void AnalizadorLandmarks::setLandmarks (const std::vector< Landmarks > & lm)
Actualiza los landmarks del objeto.
Parameters
lm landmarks nuevos.
References landmarks.
Referenced by AnalizadorSimetria::step().
Member Data Documentation
landmarks
std::vector<Landmarks> AnalizadorLandmarks::landmarks private
Vector de estructuras de tipo Landmarks.
Referenced by normalizarLandmarks(), and setLandmarks().
landmarksNorm
std::vector<Landmarks> AnalizadorLandmarks::landmarksNorm private
Vector de estructura de tipo Landmarks, pero normalizada(sin rotacion del rostro)
Referenced by calcularAsimetria(), and normalizarLandmarks().
The documentation for this class was generated from the following files:
analizadorlandmarks.h
analizadorlandmarks.cc