ProyectoVision: MiExcepcion Class Reference
MiExcepcion Class Reference
Clase de excepciones personal heredando de las excepciones estandar.
#include <estructuras.h>
Public Member Functions
MiExcepcion (const miError &_error)
const virtual char * what () const throw ()
Devuelve un texto según el tipo de error que se le pase.
Public Attributes
miError error
Detailed Description
Clase de excepciones personal heredando de las excepciones estandar.
Devuelve un texto de acuerdo al tipo de error provisto, según TipoError.
Member Function Documentation
what()
const virtual char* MiExcepcion::what () const throw () inline virtual
Devuelve un texto según el tipo de error que se le pase.
Returns
const char*
Referenced by AnalizadorSimetria::AnalizadorSimetria(), ExtractorLandmarksDlib::ExtractorLandmarksDlib(), and ExtractorLandmarksOpenCV::ExtractorLandmarksOpenCV().
The documentation for this class was generated from the following file:
estructuras.h