ProyectoVision: AnalizadorSimetria Class Reference
AnalizadorSimetria Class Reference
Clase principal del programa.
#include <analizadorsimetria.h>
Public Member Functions
AnalizadorSimetria ()
Construye un nuevo objeto de la clase Analizador Simetria. Utiliza valores por defecto.
AnalizadorSimetria (const string &)
Construye un nuevo objeto de la clase Analizador Simetria, proveyendole un archivo de configuración.
~AnalizadorSimetria ()
Destruye el objeto de la clase Analizador Simetria.
Mat getFrame ()
Devuelve el último frame obtenido.
const float getAsimetria ()
Devuelve la última asimetria calculada.
const std::vector< Landmarks > getLandmarks ()
Devuelve el ultimo vector de Landmarks calculado.
const std::vector< Landmarks > getLandmarksNorm ()
Devuelve el último vector de Landmarks normalizado.
TipoFeeder getFeeder ()
Devuelve el tipo concreto de Feeder utilizado.
TipoExtractor getExtractor ()
Devuelve el tipo de ExtractorLandmarks utilizado.
void setFeeder (TipoFeeder)
Setea tipo concreto de Feeder del analizador.
void setExtractor (TipoExtractor)
Setea el tipo concreto de Extractor del analizador.
void setNombreLog (const string &nombre)
Setea el nombre base del video del logger.
void empezarVideoLog (const TipoFeeder &)
Método para invocar un FrameLogger y comenzar la grabación.
void empezarLandmarksLog (const TipoFeeder &)
Método para invocar un LandmarksLogger y comenzar la grabación.
void stopVideoLog ()
Método para detener la grabación del FrameLogger.
void stopLandmarksLog ()
Método para detener la grabación del LandmarksLogger.
Mat step ()
Método principal a llamar para operar la clase.
void cargarConfiguracion (const string &nombreArchivo)
Método encargado de cargar el archivo de configuración y definir las propiedades del objeto.
Private Attributes
float asimetria
Propiedad que cuantiza la asimetria de un rostro.
Mat frame
Propiedad de tipo cv::Mat que contiene el ultimo fotograma obtenido.
Feeder * ptrFeeder = NULL
Puntero de la clase abstracta Feeder apuntando a la implementacion concreta.
ExtractorLandmarks * ptrExtractor = NULL
Puntero de clase abstracta ExtractorLandmarks que apunta a la implementacion concreta.
FrameLogger * ptrVideoLogger = NULL
Logger de fotogramas. Por el momento va registrando en un video.
LandmarksLogger * ptrLandmarksLogger = NULL
Logger de landmarks. Por el momento va registrando en un archivo YAML.
AnalizadorLandmarks analizadorLandmarks
Objeto que analiza y normaliza los landmarks.
std::vector< Landmarks > landmarks
Vector de landmarks actual, "crudos" como se obtuvieron del extractor.
std::vector< Landmarks > landmarksNorm
Vector de landmarks normalizado.
FileStorage fs
objeto de openCV que administra el fichero de configuracion.
string nombreFrameLogger = "Salida.avi"
Nombre por defecto del archivo de salida.
string nombreLandmarksLogger = "landmarks.yaml"
Nombre del archivo de salida de los landmarks.
string nombreConf = "config.yaml"
Nombre del archivo de configuracion.
string nombreModeloDlib = "data/shape_predictor_68_face_landmarks.dat"
Nombre del archivo del predictor utilizado por dlib.
string nombreCascadeOpenCV = "data/haarcascade_frontalface_alt2.xml"
Nombre del archivo del detector de rostros de openCV.
string nombreLBFOpenCV = "data/lbfmodel.yaml"
Nombre del archivo del detector de landmarks utilizado por openCV.
string nombreVideoFeeder = "video.avi"
Nombre del archivo de salida del logger de video.
float threshold = 2
Nivel de umbral de asimetria para registrar o no un rostro.
TipoFeeder tipoFeeder
Tipo de Deeder siendo utilizado.
TipoExtractor tipoExtractor
Tipo de ExtractorLandmarks siendo utilizado.
bool grabarVideoHabilitado = 0
Bandera para habilitar/deshabilitar el log de video.
bool grabarLandmarksHabilitado = 0
Bandera para habilitar/deshabilitar el log de landmarks.
Detailed Description
Clase principal del programa.
Se construye pasándole un archivo de configuración (por defecto "config.yaml"), el cual es encargado de elegir el tipo de feeder y extractor a utilizar. La clase además provee distintos métodos para seleccionar el tipo de feeder o extractor a utilizar. Además, permite iniciar o detener el registro en video o de landmarks. Una vez inicializada, su método principal es step(), el cual devuelve un nuevo frame, y si está habilitado el log y el extractor de landmarks, agrega el fotograma al video y analiza los nuevos landmarks.
Constructor & Destructor Documentation
AnalizadorSimetria() [1/2]
AnalizadorSimetria::AnalizadorSimetria ()
Construye un nuevo objeto de la clase Analizador Simetria. Utiliza valores por defecto.
References cargarConfiguracion(), nombreConf, OPENCV, setExtractor(), setFeeder(), tipoExtractor, tipoFeeder, WEBCAMFEEDER, and MiExcepcion::what().
AnalizadorSimetria() [2/2]
AnalizadorSimetria::AnalizadorSimetria (const string & nombrearchivo)
Construye un nuevo objeto de la clase Analizador Simetria, proveyendole un archivo de configuración.
References cargarConfiguracion(), nombreConf, OPENCV, setExtractor(), setFeeder(), tipoExtractor, tipoFeeder, WEBCAMFEEDER, and MiExcepcion::what().
~AnalizadorSimetria()
AnalizadorSimetria::~AnalizadorSimetria ()
Destruye el objeto de la clase Analizador Simetria.
References ptrExtractor, ptrFeeder, ptrLandmarksLogger, and ptrVideoLogger.
Member Function Documentation
cargarConfiguracion()
void AnalizadorSimetria::cargarConfiguracion (const string & nombreArchivo)
Método encargado de cargar el archivo de configuración y definir las propiedades del objeto.
Parameters
[in] nombreArchivo - Nombre del archivo de configuración.
References ERROR_ABRIR_CONF, fs, grabarLandmarksHabilitado, grabarVideoHabilitado, nombreCascadeOpenCV, nombreFrameLogger, nombreLandmarksLogger, nombreLBFOpenCV, nombreModeloDlib, nombreVideoFeeder, tipoExtractor, and tipoFeeder.
Referenced by AnalizadorSimetria().
empezarLandmarksLog()
void AnalizadorSimetria::empezarLandmarksLog (const TipoFeeder & tipoFeeder_)
Método para invocar un LandmarksLogger y comenzar la grabación.
References nombreLandmarksLogger, ptrLandmarksLogger, stopLandmarksLog(), and MiExcepcion::what().
Referenced by setExtractor().
empezarVideoLog()
void AnalizadorSimetria::empezarVideoLog (const TipoFeeder & tipoFeeder_)
Método para invocar un FrameLogger y comenzar la grabación.
References nombreFrameLogger, ptrVideoLogger, stopVideoLog(), and MiExcepcion::what().
Referenced by setFeeder().
getAsimetria()
const float AnalizadorSimetria::getAsimetria () inline
Devuelve la última asimetria calculada.
Returns
const float - Asimetria calculada
Referenced by main().
getExtractor()
TipoExtractor AnalizadorSimetria::getExtractor () inline
Devuelve el tipo de ExtractorLandmarks utilizado.
Returns
TipoExtractor
References ExtractorLandmarks::getExtractor().
getFeeder()
TipoFeeder AnalizadorSimetria::getFeeder () inline
Devuelve el tipo concreto de Feeder utilizado.
Returns
TipoFeeder
References Feeder::getFeeder().
getFrame()
Mat AnalizadorSimetria::getFrame () inline
Devuelve el último frame obtenido.
Returns
Mat - objeto del tipo cv::Mat conteniendo el fotograma actual
getLandmarks()
const std::vector<Landmarks> AnalizadorSimetria::getLandmarks () inline
Devuelve el ultimo vector de Landmarks calculado.
Returns
const std::vector<Landmarks> - Vector de Landmarks
Referenced by main().
getLandmarksNorm()
const std::vector<Landmarks> AnalizadorSimetria::getLandmarksNorm () inline
Devuelve el último vector de Landmarks normalizado.
Returns
const std::vector<Landmarks> - Vector de Landmarks normalizado
setExtractor()
void AnalizadorSimetria::setExtractor (TipoExtractor extractor_)
Setea el tipo concreto de Extractor del analizador.
Genera un nuevo objeto de un ExtractoLandmarks concreto. Si se elige el mismo tipo que el ya establecido, no hace nada. Si no, elimina el que se estaba utilizando y genera uno nuevo.
References DLIB, empezarLandmarksLog(), ERROR_EXTRACTOR_INICIAR, ExtractorLandmarks::getExtractor(), grabarLandmarksHabilitado, nombreCascadeOpenCV, nombreLBFOpenCV, nombreModeloDlib, OPENCV, ptrExtractor, tipoExtractor, and tipoFeeder.
Referenced by AnalizadorSimetria(), and main().
setFeeder()
void AnalizadorSimetria::setFeeder (TipoFeeder feeder_)
Setea tipo concreto de Feeder del analizador.
Genera un nuevo objeto de algun Feeder concreto. Si se elige el mismo tipo de feeder que el actual, no hace nada. Si no, elimina el que se estaba utilizando y genera uno nuevo.
References empezarVideoLog(), ERROR_FEEDER_INICIAR, Feeder::getFeeder(), grabarVideoHabilitado, KINECTFEEDER, nombreVideoFeeder, ptrFeeder, tipoFeeder, VIDEOFEEDER, and WEBCAMFEEDER.
Referenced by AnalizadorSimetria(), and main().
setNombreLog()
void AnalizadorSimetria::setNombreLog (const string & nombre) inline
Setea el nombre base del video del logger.
Parameters
nombre - Nombre base del video de salida del logger
step()
Mat AnalizadorSimetria::step ()
Método principal a llamar para operar la clase.
Este método es el encargado de actualizar toda la clase. Si hay un feeder definido, intenta obtener un nuevo frame. Si el log está habilitado, le envia el frame al logger. Si hay un extractor de landmarks, obtiene los landmarks. En caso de obtener un rostro, actualiza las propiedades de la clase y finalmente calcula la asimetría.
Returns
Mat
References analizadorLandmarks, asimetria, AnalizadorLandmarks::calcularAsimetria(), frame, Feeder::getFrame(), ExtractorLandmarks::getLandmarks(), landmarks, FrameLogger::log(), LandmarksLogger::log(), AnalizadorLandmarks::normalizarLandmarks(), ptrExtractor, ptrFeeder, ptrLandmarksLogger, ptrVideoLogger, and AnalizadorLandmarks::setLandmarks().
Referenced by main().
stopLandmarksLog()
void AnalizadorSimetria::stopLandmarksLog ()
Método para detener la grabación del LandmarksLogger.
References ptrLandmarksLogger.
Referenced by empezarLandmarksLog().
stopVideoLog()
void AnalizadorSimetria::stopVideoLog ()
Método para detener la grabación del FrameLogger.
References ptrVideoLogger.
Referenced by empezarVideoLog().
Member Data Documentation
analizadorLandmarks
AnalizadorLandmarks AnalizadorSimetria::analizadorLandmarks private
Objeto que analiza y normaliza los landmarks.
Referenced by step().
asimetria
float AnalizadorSimetria::asimetria private
Propiedad que cuantiza la asimetria de un rostro.
Referenced by step().
frame
Mat AnalizadorSimetria::frame private
Propiedad de tipo cv::Mat que contiene el ultimo fotograma obtenido.
Referenced by step().
fs
FileStorage AnalizadorSimetria::fs private
objeto de openCV que administra el fichero de configuracion.
Referenced by cargarConfiguracion().
grabarLandmarksHabilitado
bool AnalizadorSimetria::grabarLandmarksHabilitado = 0 private
Bandera para habilitar/deshabilitar el log de landmarks.
Referenced by cargarConfiguracion(), and setExtractor().
grabarVideoHabilitado
bool AnalizadorSimetria::grabarVideoHabilitado = 0 private
Bandera para habilitar/deshabilitar el log de video.
Referenced by cargarConfiguracion(), and setFeeder().
landmarks
std::vector<Landmarks> AnalizadorSimetria::landmarks private
Vector de landmarks actual, "crudos" como se obtuvieron del extractor.
Referenced by step().
landmarksNorm
std::vector<Landmarks> AnalizadorSimetria::landmarksNorm private
Vector de landmarks normalizado.
nombreCascadeOpenCV
string AnalizadorSimetria::nombreCascadeOpenCV = "data/haarcascade_frontalface_alt2.xml" private
Nombre del archivo del detector de rostros de openCV.
Referenced by cargarConfiguracion(), and setExtractor().
nombreConf
string AnalizadorSimetria::nombreConf = "config.yaml" private
Nombre del archivo de configuracion.
Referenced by AnalizadorSimetria().
nombreFrameLogger
string AnalizadorSimetria::nombreFrameLogger = "Salida.avi" private
Nombre por defecto del archivo de salida.
Referenced by cargarConfiguracion(), and empezarVideoLog().
nombreLandmarksLogger
string AnalizadorSimetria::nombreLandmarksLogger = "landmarks.yaml" private
Nombre del archivo de salida de los landmarks.
Referenced by cargarConfiguracion(), and empezarLandmarksLog().
nombreLBFOpenCV
string AnalizadorSimetria::nombreLBFOpenCV = "data/lbfmodel.yaml" private
Nombre del archivo del detector de landmarks utilizado por openCV.
Referenced by cargarConfiguracion(), and setExtractor().
nombreModeloDlib
string AnalizadorSimetria::nombreModeloDlib = "data/shape_predictor_68_face_landmarks.dat" private
Nombre del archivo del predictor utilizado por dlib.
Referenced by cargarConfiguracion(), and setExtractor().
nombreVideoFeeder
string AnalizadorSimetria::nombreVideoFeeder = "video.avi" private
Nombre del archivo de salida del logger de video.
Referenced by cargarConfiguracion(), and setFeeder().
ptrExtractor
ExtractorLandmarks* AnalizadorSimetria::ptrExtractor = NULL private
Puntero de clase abstracta ExtractorLandmarks que apunta a la implementacion concreta.
Referenced by setExtractor(), step(), and ~AnalizadorSimetria().
ptrFeeder
Feeder* AnalizadorSimetria::ptrFeeder = NULL private
Puntero de la clase abstracta Feeder apuntando a la implementacion concreta.
Referenced by setFeeder(), step(), and ~AnalizadorSimetria().
ptrLandmarksLogger
LandmarksLogger* AnalizadorSimetria::ptrLandmarksLogger = NULL private
Logger de landmarks. Por el momento va registrando en un archivo YAML.
Referenced by empezarLandmarksLog(), step(), stopLandmarksLog(), and ~AnalizadorSimetria().
ptrVideoLogger
FrameLogger* AnalizadorSimetria::ptrVideoLogger = NULL private
Logger de fotogramas. Por el momento va registrando en un video.
Referenced by empezarVideoLog(), step(), stopVideoLog(), and ~AnalizadorSimetria().
threshold
float AnalizadorSimetria::threshold = 2 private
Nivel de umbral de asimetria para registrar o no un rostro.
tipoExtractor
TipoExtractor AnalizadorSimetria::tipoExtractor private
Tipo de ExtractorLandmarks siendo utilizado.
Referenced by AnalizadorSimetria(), cargarConfiguracion(), and setExtractor().
tipoFeeder
TipoFeeder AnalizadorSimetria::tipoFeeder private
Tipo de Deeder siendo utilizado.
Referenced by AnalizadorSimetria(), cargarConfiguracion(), setExtractor(), and setFeeder().
The documentation for this class was generated from the following files:
analizadorsimetria.h
analizadorsimetria.cc