ProyectoVision: Feeder Class Reference
Feeder Class Reference abstract
Clase abstracta para proveer obtener nuevos mats.
#include <feeder.h>
Public Member Functions
Feeder ()
Construye un nuevo objeto de la clase abstracta Feeder.
virtual ~Feeder ()
Destruye el objeto de la clase abstracta Feeder.
virtual const TipoFeeder getFeeder ()=0
Devuelve el TipoFeeder del feeder implementado.
virtual const Mat getFrame ()=0
Devuelve el frame actual.
Private Attributes
Mat frame
Estructura que contiene el frame actual.
Detailed Description
Clase abstracta para proveer obtener nuevos mats.
Clase abstracta para utilizar como interfaz a las implementaciones concretas. Provee dos métodos básicos que todas las clases utilizarán.
Constructor & Destructor Documentation
Feeder()
Feeder::Feeder () inline
Construye un nuevo objeto de la clase abstracta Feeder.
~Feeder()
virtual Feeder::~Feeder () inline virtual
Destruye el objeto de la clase abstracta Feeder.
Member Function Documentation
getFeeder()
virtual const TipoFeeder Feeder::getFeeder () pure virtual
Devuelve el TipoFeeder del feeder implementado.
Returns
const TipoFeeder
Implemented in KinectFeeder, VideoFeeder, and WebcamFeeder.
Referenced by AnalizadorSimetria::getFeeder(), and AnalizadorSimetria::setFeeder().
getFrame()
virtual const Mat Feeder::getFrame () pure virtual
Devuelve el frame actual.
Returns
const Mat
Implemented in KinectFeeder, VideoFeeder, and WebcamFeeder.
Referenced by AnalizadorSimetria::step().
Member Data Documentation
frame
Mat Feeder::frame private
Estructura que contiene el frame actual.
The documentation for this class was generated from the following file:
feeder.h