name: Doxygen GitHub Pages Deploy Action

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: DenverCoder1/doxygen-github-pages-action@main
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: gh-pages
          folder: docs/html
        # - uses: mattnotmitt/doxygen-action@1.9.4
        #   with:
        #       doxyfile-path: 'Doxyfile'
        #       additional-packages: graphviz, plantuml